development:
  # adapter: async
  adapter: solid_cable
  silence_polling: true

test:
  adapter: test

production:
  # adapter: redis
  adapter: solid_cable
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: smart_recipes_production
